# Site settings
title: Internet Clubhouse
email: jsnhff+internetclubhouse@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place for making, design, and jokes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://internetclub.house" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
